// Generated by scripts/sync-models.mjs from generation/catalog/models/*. Do not edit.
import type { ModelEntry } from "./types";

import m0 from "./models/dop";
import m1 from "./models/flux-2";
import m2 from "./models/flux-3";
import m3 from "./models/grok-imagine-2";
import m4 from "./models/grok-imagine-video-1.5";
import m5 from "./models/happy-horse-1";
import m6 from "./models/happy-horse-1.1";
import m7 from "./models/ideogram-4";
import m8 from "./models/kling-2.5";
import m9 from "./models/kling-2.6";
import m10 from "./models/kling-3";
import m11 from "./models/kling-o1";
import m12 from "./models/kling-o3";
import m13 from "./models/ltx-2.5-fast";
import m14 from "./models/ltx-2.5-pro";
import m15 from "./models/minimax-h3";
import m16 from "./models/minimax-hailuo-2.3";
import m17 from "./models/pixverse-6";
import m18 from "./models/qwen-image-3";
import m19 from "./models/recraft-4.1";
import m20 from "./models/seedance-2";
import m21 from "./models/seedance-2.5";
import m22 from "./models/soul";
import m23 from "./models/wan-2.6";
import m24 from "./models/wan-2.7";
import m25 from "./models/wan-3";
import m26 from "./models/wan-3-prime";
import m27 from "./models/z-image-turbo";

const LAST = Number.MAX_SAFE_INTEGER;

const installed: (ModelEntry | ModelEntry[])[] = [m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, m21, m22, m23, m24, m25, m26, m27];

export const MODELS: readonly ModelEntry[] = installed
  .flat()
  .sort((a, b) => (a.order ?? LAST) - (b.order ?? LAST));
