// Scans generation/catalog/models/*.ts and writes:
//   - generation/catalog/models.generated.ts  (the MODELS barrel)
//   - generation/catalog/models/registry.json (one shadcn registry item per model file)
// Runs from next.config.ts on every dev/build, so `shadcn add <model>` needs no manual wiring.
import { existsSync, mkdirSync, readdirSync, readFileSync, watch, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MODELS_DIR = join(ROOT, "generation/catalog/models");
const BARREL = join(ROOT, "generation/catalog/models.generated.ts");
const REGISTRY = join(MODELS_DIR, "registry.json");
const TARGET_DIR = "~/generation/catalog/models";

export function syncModels() {
  // A bare install ships no model files; an empty barrel is still a valid catalog.
  mkdirSync(MODELS_DIR, { recursive: true });
  const names = readdirSync(MODELS_DIR)
    .filter((file) => file.endsWith(".ts") && !file.endsWith(".d.ts"))
    .map((file) => file.slice(0, -3))
    .sort();

  const barrel = renderBarrel(names);
  const registry = JSON.stringify(renderRegistry(names), null, 2) + "\n";
  const changed = writeIfChanged(BARREL, barrel) | writeIfChanged(REGISTRY, registry);
  return { names, changed: Boolean(changed) };
}

/** Dev only: re-sync when a model file is added or removed (e.g. by `shadcn add`). */
export function watchModels() {
  mkdirSync(MODELS_DIR, { recursive: true });
  let timer;
  watch(MODELS_DIR, (_event, file) => {
    if (!file || !file.endsWith(".ts")) return;
    clearTimeout(timer);
    timer = setTimeout(() => {
      const { names, changed } = syncModels();
      if (changed) console.log(`[models] ${names.length} model files, barrel updated`);
    }, 150);
  }).unref();
}

function renderBarrel(names) {
  const imports = names.map((name, i) => `import m${i} from "./models/${name}";`).join("\n");
  const list = names.map((_, i) => `m${i}`).join(", ");
  return `// Generated by scripts/sync-models.mjs from generation/catalog/models/*. Do not edit.
import type { ModelEntry } from "./types";

${imports}

const LAST = Number.MAX_SAFE_INTEGER;

const installed: (ModelEntry | ModelEntry[])[] = [${list}];

export const MODELS: readonly ModelEntry[] = installed
  .flat()
  .sort((a, b) => (a.order ?? LAST) - (b.order ?? LAST));
`;
}

function renderRegistry(names) {
  const file = (name) => ({ path: `${name}.ts`, type: "registry:file", target: `${TARGET_DIR}/${name}.ts` });
  const bundle = {
    name: "models",
    type: "registry:item",
    title: "All models",
    description: "Every model in the Higgsfield catalog. Install alongside a template item.",
    categories: ["model"],
    files: names.map(file),
  };
  return {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    items: [bundle, ...names.map((name) => {
      const source = readFileSync(join(MODELS_DIR, `${name}.ts`), "utf8");
      // Catalog object fields use two-space indentation; exclude nested mode IDs.
      const factory = [...source.matchAll(/(?:imageModel|videoModel)\(\s*"([^"]+)",\s*"([^"]+)"/g)];
      const ids = [...matchAll(source, /^ {2}id:\s*"([^"]+)"/gm), ...factory.map((m) => m[1])];
      const labels = [...matchAll(source, /^ {2}label:\s*"([^"]+)"/gm), ...factory.map((m) => m[2])];
      const surface = source.includes("imageModel(") || /surface:\s*"image"/.test(source) ? "image" : "video";
      const title = labels[0] ?? name;
      return {
        name,
        type: "registry:item",
        title,
        description: `${labels.join(", ") || title} ${surface} model for Higgsfield app templates. Requires a template item (studio).`,
        categories: ["model", surface],
        meta: { ids, surface },
        files: [file(name)],
      };
    })],
  };
}

function matchAll(source, regex) {
  return [...source.matchAll(regex)].map((match) => match[1]);
}

function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return 0;
  writeFileSync(path, content);
  return 1;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const { names, changed } = syncModels();
  console.log(`[models] ${names.length} model files${changed ? ", updated barrel + registry" : ", up to date"}`);
}
